name = "portfolio-showcase"
pages_build_output_dir = "public"
compatibility_date = "2024-12-30"

[[d1_databases]]
binding = "DB"
database_name = "portfolio-showcase-db"
database_id = "2b544f1c-fc16-4be3-bf14-2f0680e738b4"

# R2 对象存储（页面图片/二维码/PDF 分块）
[[r2_buckets]]
binding = "R2"
bucket_name = "portfolio-showcase-files"
